# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 820)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 820))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainWidget = QtWidgets.QWidget(self.centralwidget)
        self.mainWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.mainWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.mainWidget.setObjectName("mainWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hly_head = QtWidgets.QHBoxLayout()
        self.hly_head.setObjectName("hly_head")
        self.head_widget = QtWidgets.QWidget(self.mainWidget)
        self.head_widget.setMinimumSize(QtCore.QSize(0, 60))
        self.head_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.head_widget.setStyleSheet("background-color: rgb(198, 47, 47);")
        self.head_widget.setObjectName("head_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.head_widget)
        self.horizontalLayout.setContentsMargins(15, 10, 15, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.head_widget)
        self.widget.setMinimumSize(QtCore.QSize(225, 0))
        self.widget.setMaximumSize(QtCore.QSize(225, 16777215))
        self.widget.setObjectName("widget")
        self.hly_headLogo = QtWidgets.QHBoxLayout(self.widget)
        self.hly_headLogo.setContentsMargins(0, 0, 0, 0)
        self.hly_headLogo.setSpacing(0)
        self.hly_headLogo.setObjectName("hly_headLogo")
        self.lb_logo = QtWidgets.QLabel(self.widget)
        self.lb_logo.setMinimumSize(QtCore.QSize(155, 30))
        self.lb_logo.setMaximumSize(QtCore.QSize(155, 30))
        self.lb_logo.setStyleSheet("border-image: url(:/icon/Resource/logo1.png);")
        self.lb_logo.setText("")
        self.lb_logo.setObjectName("lb_logo")
        self.hly_headLogo.addWidget(self.lb_logo)
        spacerItem = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hly_headLogo.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.head_widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_2.setObjectName("widget_2")
        self.hly_preOrNextOp = QtWidgets.QHBoxLayout(self.widget_2)
        self.hly_preOrNextOp.setContentsMargins(0, 0, 10, 0)
        self.hly_preOrNextOp.setSpacing(0)
        self.hly_preOrNextOp.setObjectName("hly_preOrNextOp")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton.setStyleSheet("border:1px solid #aaa;\n"
"border-image: url(:/icon/Resource/preOperation.png);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.hly_preOrNextOp.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_2.setStyleSheet("border-image: url(:/icon/Resource/nextOperation1.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.hly_preOrNextOp.addWidget(self.pushButton_2)
        self.horizontalLayout.addWidget(self.widget_2)
        self.hly_search = QtWidgets.QHBoxLayout()
        self.hly_search.setObjectName("hly_search")
        self.horizontalLayout.addLayout(self.hly_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.vly_userimage = QtWidgets.QVBoxLayout()
        self.vly_userimage.setSpacing(0)
        self.vly_userimage.setObjectName("vly_userimage")
        self.horizontalLayout.addLayout(self.vly_userimage)
        self.btn_signin = QtWidgets.QPushButton(self.head_widget)
        self.btn_signin.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_signin.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_signin.setLayoutDirection(QtCore.Qt.RightToLeft)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/Resource/down2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_signin.setIcon(icon)
        self.btn_signin.setObjectName("btn_signin")
        self.horizontalLayout.addWidget(self.btn_signin)
        self.btn_setting = QtWidgets.QPushButton(self.head_widget)
        self.btn_setting.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_setting.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_setting.setText("")
        self.btn_setting.setObjectName("btn_setting")
        self.horizontalLayout.addWidget(self.btn_setting)
        self.line = QtWidgets.QFrame(self.head_widget)
        self.line.setMinimumSize(QtCore.QSize(1, 0))
        self.line.setMaximumSize(QtCore.QSize(1, 30))
        self.line.setStyleSheet("")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.btn_minwin = QtWidgets.QPushButton(self.head_widget)
        self.btn_minwin.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_minwin.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_minwin.setText("")
        self.btn_minwin.setObjectName("btn_minwin")
        self.horizontalLayout.addWidget(self.btn_minwin)
        self.btn_maxwin = QtWidgets.QPushButton(self.head_widget)
        self.btn_maxwin.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_maxwin.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_maxwin.setText("")
        self.btn_maxwin.setObjectName("btn_maxwin")
        self.horizontalLayout.addWidget(self.btn_maxwin)
        self.btn_closewin = QtWidgets.QPushButton(self.head_widget)
        self.btn_closewin.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_closewin.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_closewin.setText("")
        self.btn_closewin.setObjectName("btn_closewin")
        self.horizontalLayout.addWidget(self.btn_closewin)
        self.hly_head.addWidget(self.head_widget)
        self.verticalLayout_2.addLayout(self.hly_head)
        self.hly_body = QtWidgets.QHBoxLayout()
        self.hly_body.setContentsMargins(-1, 0, -1, -1)
        self.hly_body.setSpacing(0)
        self.hly_body.setObjectName("hly_body")
        self.vly_leftBar = QtWidgets.QVBoxLayout()
        self.vly_leftBar.setSpacing(0)
        self.vly_leftBar.setObjectName("vly_leftBar")
        self.hly_body.addLayout(self.vly_leftBar)
        self.body_stackedWidget = QtWidgets.QStackedWidget(self.mainWidget)
        self.body_stackedWidget.setObjectName("body_stackedWidget")
        self.page_findMusic = QtWidgets.QWidget()
        self.page_findMusic.setObjectName("page_findMusic")
        self.hly_findMusic = QtWidgets.QHBoxLayout(self.page_findMusic)
        self.hly_findMusic.setContentsMargins(0, 0, 0, 0)
        self.hly_findMusic.setObjectName("hly_findMusic")
        self.body_stackedWidget.addWidget(self.page_findMusic)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.body_stackedWidget.addWidget(self.page_2)
        self.hly_body.addWidget(self.body_stackedWidget)
        self.verticalLayout_2.addLayout(self.hly_body)
        self.hly_bottom = QtWidgets.QHBoxLayout()
        self.hly_bottom.setSpacing(0)
        self.hly_bottom.setObjectName("hly_bottom")
        self.broadcast_widget = QtWidgets.QWidget(self.mainWidget)
        self.broadcast_widget.setMinimumSize(QtCore.QSize(0, 60))
        self.broadcast_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.broadcast_widget.setStyleSheet("background-color: #f0f0f0;")
        self.broadcast_widget.setObjectName("broadcast_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.broadcast_widget)
        self.horizontalLayout_3.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_preSong = QtWidgets.QPushButton(self.broadcast_widget)
        self.btn_preSong.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_preSong.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_preSong.setText("")
        self.btn_preSong.setObjectName("btn_preSong")
        self.horizontalLayout_3.addWidget(self.btn_preSong)
        self.btn_play = QtWidgets.QPushButton(self.broadcast_widget)
        self.btn_play.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_play.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_play.setText("")
        self.btn_play.setObjectName("btn_play")
        self.horizontalLayout_3.addWidget(self.btn_play)
        self.btn_nextSong = QtWidgets.QPushButton(self.broadcast_widget)
        self.btn_nextSong.setMinimumSize(QtCore.QSize(35, 35))
        self.btn_nextSong.setMaximumSize(QtCore.QSize(35, 35))
        self.btn_nextSong.setText("")
        self.btn_nextSong.setObjectName("btn_nextSong")
        self.horizontalLayout_3.addWidget(self.btn_nextSong)
        self.lb_nowTime = QtWidgets.QLabel(self.broadcast_widget)
        self.lb_nowTime.setObjectName("lb_nowTime")
        self.horizontalLayout_3.addWidget(self.lb_nowTime)
        self.slider_playProgress = QtWidgets.QSlider(self.broadcast_widget)
        self.slider_playProgress.setOrientation(QtCore.Qt.Horizontal)
        self.slider_playProgress.setObjectName("slider_playProgress")
        self.horizontalLayout_3.addWidget(self.slider_playProgress)
        self.lb_sumTime = QtWidgets.QLabel(self.broadcast_widget)
        self.lb_sumTime.setObjectName("lb_sumTime")
        self.horizontalLayout_3.addWidget(self.lb_sumTime)
        self.lb_volume = QtWidgets.QLabel(self.broadcast_widget)
        self.lb_volume.setMinimumSize(QtCore.QSize(25, 25))
        self.lb_volume.setMaximumSize(QtCore.QSize(25, 25))
        self.lb_volume.setStyleSheet("border-image: url(:/icon/Resource/volume.png);")
        self.lb_volume.setText("")
        self.lb_volume.setObjectName("lb_volume")
        self.horizontalLayout_3.addWidget(self.lb_volume)
        self.slider_volume = QtWidgets.QSlider(self.broadcast_widget)
        self.slider_volume.setMinimumSize(QtCore.QSize(120, 0))
        self.slider_volume.setMaximumSize(QtCore.QSize(120, 16777215))
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName("slider_volume")
        self.horizontalLayout_3.addWidget(self.slider_volume)
        self.btn_playOder = QtWidgets.QPushButton(self.broadcast_widget)
        self.btn_playOder.setMinimumSize(QtCore.QSize(30, 25))
        self.btn_playOder.setMaximumSize(QtCore.QSize(30, 25))
        self.btn_playOder.setText("")
        self.btn_playOder.setObjectName("btn_playOder")
        self.horizontalLayout_3.addWidget(self.btn_playOder)
        self.btn_playList = QtWidgets.QPushButton(self.broadcast_widget)
        self.btn_playList.setMinimumSize(QtCore.QSize(25, 25))
        self.btn_playList.setMaximumSize(QtCore.QSize(25, 25))
        self.btn_playList.setText("")
        self.btn_playList.setObjectName("btn_playList")
        self.horizontalLayout_3.addWidget(self.btn_playList)
        self.hly_bottom.addWidget(self.broadcast_widget)
        self.verticalLayout_2.addLayout(self.hly_bottom)
        self.verticalLayout.addWidget(self.mainWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.body_stackedWidget.setCurrentIndex(0)
        self.btn_closewin.clicked.connect(MainWindow.close)
        self.btn_minwin.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_signin.setText(_translate("MainWindow", "立即登录"))
        self.lb_nowTime.setText(_translate("MainWindow", "01.01"))
        self.lb_sumTime.setText(_translate("MainWindow", "03.24"))
import rec_rc
